# Generated by Django 5.1.7 on 2025-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_alter_developer_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
